### ISSUE TITLE
 ios shows 2 Launchimages of different sizes

### ISSUE THREAD

**Issue by woochans** [jonbhanson/flutter_native_splash#528] opened 2023-03-09 09:22 UTC
A few seconds after the first screen is shown, another screen is shown in a different position and size.
Why are there different launchimages?

Do you know how?
what should i do?

**Device (please complete the following information):**
 - Device: iPhone Xs Max
 - OS: iOS15.6.1

**Screenshots**

![DD6D02B9-A525-428E-9C1D-6D4FEB1BF39E](https://user-images.githubusercontent.com/112914914/223976785-66ed79d8-2dc7-4d9e-821d-187728b366be.png)

![82101517-2686-4F0B-818B-2392B2C4B3F5](https://user-images.githubusercontent.com/112914914/223976870-dbbcf7df-3170-4be9-8ec7-9a8539712368.png)

**Comment by jonbhanson** [comment] 2023-03-09 14:01
Was your app created prior to Flutter 2.5?  You may need to follow [these instructions](https://docs.flutter.dev/development/platform-integration/android/splash-screen-migration) to migrate the splash screen to work with the current version of Flutter.  Can you please let me know if this works?  I may need to add this to this package's FAQ.

**Comment by woochans** [comment] 2023-03-10 02:49
My version is Flutter 3.7.3.
Unfortunately, what you've told me seems to be about android.

Are there any cases where the Launch Image is displayed twice on ios?

**Comment by xMISSJ** [comment] 2023-03-14 12:38
> My version is Flutter 3.7.3. Unfortunately, what you've told me seems to be about android.
> 
> Are there any cases where the Launch Image is displayed twice on ios?

I'm experiencing the same issue, also Flutter 3.7.3. First, the image is displayed in a smaller size, then in the size I want. I tried deleting the splash and recreating it, flutter clean and etc, but nothing seems to work.

**Comment by jonbhanson** [comment] 2023-03-14 12:50
Please check the [I see a flash of the wrong splash screen on iOS](https://pub.dev/packages/flutter_native_splash#i-see-a-flash-of-the-wrong-splash-screen-on-ios) question in the readme's faq.

**Comment by jonbhanson** [comment] 2023-03-28 21:53
If it is not fixed by that link above, could one of you send me a minimal project that reproduces this problem so I can try to get to the bottom of this issue?

**Comment by jonbhanson** [comment] 2023-04-09 14:10
Closed due to inactivity.  Feel free to reopen if you are still having trouble.

**Closed by jonbhanson** 2023-04-09 14:10 UTC
