### ISSUE TITLE
[Bug]shift position

### ISSUE THREAD

**Issue by shinriyo** [jonbhanson/flutter_native_splash#86] opened 2020-09-14 10:01 UTC
I guess it is dependence of Android machine.

Galaxy S10

vertically shift bug

**Comment by shinriyo** [comment] 2020-09-14 10:02
like this
https://stackoverflow.com/questions/54751605/android-splash-screen-shifts

**Comment by shinriyo** [comment] 2020-09-14 10:05
`android:windowBackground`
to 
`android:background`
?

**Comment by jonbhanson** [comment] 2021-01-13 16:35
Can you give instructions on how to reproduce?

**Comment by shinriyo** [comment] 2021-01-13 23:31
@jonbhanson 
how to reproduce is README's Usage

**Comment by mmmcorpsvit** [comment] 2021-01-14 11:00
try check: https://github.com/flutter/flutter/issues/46486#issuecomment-760117674

**Comment by jonbhanson** [comment] 2021-01-14 12:48
@shinriyo I created a new project using the instructions in the readme, but I was not able to reproduce the shift you described.

**Comment by shinriyo** [comment] 2021-01-14 13:10
do you use Galaxy S10?

**Comment by jonbhanson** [comment] 2021-01-14 14:49
I don't have a physical Galaxy S10, but I tried it with an emulated S10.

**Comment by shinriyo** [comment] 2021-01-16 00:45
@jonbhanson It happened in physical Galaxy S10, but I don't have it too.
in the Previous project, a worker had Galaxy S10, but I moved the project I can't try it now.

@mmmcorpsvit 's link may help the problem.

**Comment by jonbhanson** [comment] 2021-01-18 14:03
@shinriyo thanks for the info.  Since I have not been able to reproduce, I will close this ticket.  Feel free to reopen if you can give steps to reproduce.

**Closed by jonbhanson** 2021-01-18 14:03 UTC
Labels: bug, waiting response
