### ISSUE TITLE
New `preserve()` and `remove()` show black screen for a few seconds

### ISSUE THREAD

**Issue by jezsung** [jonbhanson/flutter_native_splash#353] opened 2022-05-16 15:39 UTC
The `preserve()` and `remove()` functions replacing the old `removeAfter()` show a black screen for a second while the old one doesn't. I'm running code inside `runZonedGuarded()`.

**Comment by jonbhanson** [comment] 2022-05-17 12:24
Can you advise how to reproduce or provide a code sample that reproduces this problem?  Does this package's example have this same problem?

**Comment by boyma-examples** [comment] 2022-05-21 20:23
its not working at all...
steps to reproduce:

```
mainRunApp(Flavor flavor) async {
  F.appFlavor = flavor;
  WidgetsBinding widgetsBinding = WidgetsFlutterBinding.ensureInitialized();
  FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);
  runApp(MyApp());
}
```

somewhere in widget:
```
Future.delayed(const Duration(milliseconds: 5555)).then(
                (value) => FlutterNativeSplash.remove(),
              );
```

logo appears for a few seconds then we can see only background
Android 12 emulator

**Comment by boyma-examples** [comment] 2022-05-21 20:53
upd solved ussue^
need to delete in AndroidManifest.xml
```
<meta-data android:name="io.flutter.embedding.android.SplashScreenDrawable" android:resource="@drawable/launch_background"/>
```
maybe in some old projects this was by default

**Comment by jonbhanson** [comment] 2022-05-22 13:34
@jezsung @robertoltrocha @fraca98 does @boyma-examples solution work for you?  If not, can you advise how to reproduce this problem?

**Comment by jonbhanson** [comment] 2022-05-29 14:12
Closing as this seems to be resolved.  Feel free to open a new ticket if you are still having a problem.

**Closed by jonbhanson** 2022-05-29 14:12 UTC
