### ISSUE TITLE
Splash Screen for Desktop Apps

### ISSUE THREAD

**Issue by itsahmed-dev** [jonbhanson/flutter_native_splash#417] opened 2022-09-07 12:18 UTC
I would like to see the option to make splash screens for desktop apps. Thanks

**Comment by jonbhanson** [comment] 2022-09-07 13:58
Duplicate of #168.

**Closed by jonbhanson** 2022-09-07 13:58 UTC

**Comment by itsahmed-dev** [comment] 2022-09-09 09:14
Oh. Ok
