### ISSUE TITLE
CantFindAppDelegatePath error, when running the flutter pub run flutter_native_splash:create command

### ISSUE THREAD

**Issue by idevChandra6** [jonbhanson/flutter_native_splash#125] opened 2021-02-03 21:48 UTC
**Describe the bug**
When running the `flutter pub run flutter_native_splash:create`, `CantFindAppDelegatePath` error gets printed.

**To Reproduce**
1. Add `flutter_native_splash: ^0.2.9` to `pubspec.yaml`
2. Add below lines in `pubspec.yaml` 

```
flutter_native_splash:
  color: "#42a5f5"
  image: assets/images/splash_inset.png
  android: true
  ios: true

```
3. Run `flutter pub get` command
4. Run `flutter pub run flutter_native_splash:create`

You should see mentioned error.

**Expected behavior**
The `flutter pub run flutter_native_splash:create` should run with out error, creating the launch images.

**Screenshots**

```
# flutter pub run flutter_native_splash:create
[Android] Creating splash images
[Android] Updating android/app/src/main/res/drawable/launch_background.xml with splash image path
[Android] Updating android/app/src/main/res/values/colors.xml with color for splash screen background
[Android] Updating styles.xml with full screen mode setting
[iOS] Creating splash images
[iOS] Updating LaunchScreen.storyboard with width, and height
Unhandled exception:
*** ERROR [flutter_native_splash] ***
CantFindAppDelegatePath
Not able to determinate AppDelegate path.
#0      _objectiveCOrSwift (package:flutter_native_splash/ios.dart:320:5)
#1      _applyAppDelegate (package:flutter_native_splash/ios.dart:295:27)
#2      _createiOSSplash (package:flutter_native_splash/ios.dart:49:9)
<asynchronous suspension>
#3      tryCreateSplashByConfig (package:flutter_native_splash/supported_platform.dart:52:11)
<asynchronous suspension>
#4      tryCreateSplash (package:flutter_native_splash/supported_platform.dart:26:9)
<asynchronous suspension>
#5      createSplash (package:flutter_native_splash/flutter_native_splash.dart:17:9)
#6      main (file:///Users/myuser/.pub-cache/hosted/pub.dartlang.org/flutter_native_splash-0.2.9/bin/create.dart:5:3)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
pub finished with exit code 255
```

**Device (please complete the following information):**
 - Device: iPhone 11 Simulator, iPhone 12 mini Physical Device
 - OS: iOS 14.0

**Flutter doctor**

Flutter Doctor report these two issues. But I do have them. I get these errors everytime. 

```
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.

```

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-US)
    • Flutter version 1.22.4 at /Users/cpoleped/development/flutter
    • Framework revision 1aafb3a8b9 (3 months ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/cpoleped/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • iPhone 11 (mobile) • 645554E2-32AE-4876-9613-9FE4F7B62773 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

! Doctor found issues in 2 categories.
```

**Additional context**
Not any!

**Comment by YangLuYang** [comment] 2021-02-04 07:16
same issue, Is there any solution ?

**Comment by jonbhanson** [comment] 2021-02-04 12:29
I created a new Flutter project with the steps you outlined, but unfortunately I was not able to reproduce the problem.  That exception is triggered when the package is not able to locate 'ios/Runner/AppDelegate.m' or 'ios/Runner/AppDelegate.swift' depending if iOS app is built on Objective-C or Swift, respectively.  Was this file moved or renamed?

**Comment by YangLuYang** [comment] 2021-02-04 13:10
I make flutter project as module, my workspace folder like this. `aiplay` is my iOS project
![image](https://user-images.githubusercontent.com/17721603/106896803-03361f80-672d-11eb-8c95-badf1ed8810d.png)

**Comment by jonbhanson** [comment] 2021-02-04 13:28
OK, @YangLuYang, I have not used Flutter modules yet, so you may have to help me understand.  As I understand you have a native iOS app `aiplay` that has `flutter_module` integrated in it.  Is this correct?  If this is the case, I think the LaunchScreen.storyboard for your final app resides in the `aiplay` native app.  The `flutter_module` will have a .ios/Runner/Base.lproj/LaunchScreen.storyboard, but the .ios folder exists to run a standalone version of the module.  As the [docs state](https://flutter.dev/docs/development/add-to-app/ios/project-setup), _" Add custom iOS code to your own existing application’s project or to a plugin, not to the module’s .ios/ directory. Changes made in your module’s .ios/ directory do not appear in your existing iOS project using the module, and may be overwritten by Flutter."_  So even if this package modified the splash screen in the module, it would not appear in the final app.  Thoughts?

**Comment by YangLuYang** [comment] 2021-02-04 14:39
@jonbhanson Yes, I think your are correct, native will present flutter after a `ViewController` invoke `viewWillLayoutSubviews` method when native app has `flutter_module` integrated in.  So the `LaunchScreen.storyboard` should in the `aiplay` native app.

**Comment by jonbhanson** [comment] 2021-02-04 16:09
@idevChandra6 are you using a Flutter module in a native app?

**Comment by jonbhanson** [comment] 2021-02-08 13:22
This has been fixed in the latest update.

**Closed** 2021-02-08 13:22 UTC
Labels: waiting response

**Comment by zeeshan-rsys** [comment] 2022-10-26 16:02
xcode 13.4

development target version 12.0



<img width="800" alt="Screenshot 2022-10-25 at 8 39 37 PM" src="https://user-images.githubusercontent.com/101088061/197812829-57299c3c-624e-45b8-865b-67a3011c5065.png">

<details>
  <summary>Logs</summary>



```
❯ flutter doctor -v
[✓] Flutter (Channel stable, 3.3.5, on macOS 12.5 21G72 darwin-arm, locale en-IN)
    • Flutter version 3.3.5 on channel stable at /Users/radiansys/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d9111f6402 (6 days ago), 2022-10-19 12:27:13 -0700
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/radiansys/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Users/radiansys/Downloads/Xcode.app/Contents/Developer
    • Build 13F17a
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • 3D524B95-EE05-45B1-8269-9C87F3A95CD9 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.5 21G72
      darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>



<img width="575" alt="Screenshot 2022-10-26 at 9 29 57 PM" src="https://user-images.githubusercontent.com/101088061/198076512-6d60b9ef-0a45-4dd3-a86f-f9512f8c3a40.png">
<img width="373" alt="Screenshot 2022-10-26 at 9 30 14 PM" src="https://user-images.githubusercontent.com/101088061/198076520-3aaa78b6-5daf-49cb-b440-5bec17ad769c.png">

**Comment by boris1690** [comment] 2022-10-26 21:54
Hi Guys,

I have the same error when run in xcode

<img width="705" alt="Screenshot 2022-10-26 at 16 53 58" src="https://user-images.githubusercontent.com/5614247/198145834-c2011516-5cc3-4cc1-af05-4e0e58250291.png">

**Comment by jonbhanson** [comment] 2022-10-30 14:18
@zeeshan-rsys @boris1690 your problem is not related to this ticket.  Please open a new ticket with all the requested information in the report template.
