### ISSUE TITLE
WARNING: found an existing <meta name="viewport"> tag. Flutter Web uses its own viewport ...

### ISSUE THREAD

**Issue by iapicca** [jonbhanson/flutter_native_splash#526] opened 2023-03-04 09:43 UTC
### DESCRIPTION

Running application shows warning 
```console
WARNING: found an existing <meta name="viewport"> tag. Flutter Web uses its own viewport configuration for better compatibility with Flutter. This tag will be replaced.
```

### STEP TO REPRODUCE

- create app running `flutter create flutter_native_splash_issue`
- add `flutter_native_splash` to the dependencies
- add `splashscreen.yaml` file to the project
- create splash screen running `flutter pub run flutter_native_splash:create --path=splashscreen.yaml`
- run the app `flutter run -d chrome`

[code sample](https://github.com/iapicca/flutter_native_splash_issue)

```console
[!] Flutter (Channel stable, 3.7.6, on macOS 13.2.1 22D68 darwin-arm64, locale en-EE)
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.19.3/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/yakforward/fvm/versions/stable. Consider adding
      /Users/yakforward/fvm/versions/stable/bin to the front of your path.
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.76.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

**Comment by jonbhanson** [comment] 2023-03-05 17:19
Duplicate of #359 and #397.

**Closed by jonbhanson** 2023-03-05 17:19 UTC

**Comment by cl0v** [comment] 2025-05-15 16:27
2025 and the warning still...

**Comment by iapicca** [comment] 2025-05-16 05:23
> Duplicate of [#359](https://github.com/jonbhanson/flutter_native_splash/issues/359) and [#397](https://github.com/jonbhanson/flutter_native_splash/issues/397).


@jonbhanson
I understand it's a duplicate, but both issues are closed and the problem still unresolved,
the only "solution"S offered are

- https://github.com/jonbhanson/flutter_native_splash/issues/359

> At this time, I only know of two choices:
> 
> 1. Leave the meta tag, in which case you will receive the warning.  However, the splash screen will work fine in web.
> 2. Remove the meta tag, which will remove the warning, However, the splash screen will change size in web.

- https://github.com/jonbhanson/flutter_native_splash/issues/397

a [closed PR](https://github.com/jonbhanson/flutter_native_splash/pull/769)

is there any chance for the issue to be actually solved?
