### ISSUE TITLE
Full Screen splash image in Android

### ISSUE THREAD

**Issue by vukhacbiet** [jonbhanson/flutter_native_splash#129] opened 2021-02-09 10:04 UTC
I created a splash image at 2400x2400px and in my pubspec.yaml: 
```

flutter_native_splash:
  image: link/to/splash.png
  color: ffffff
  fullscreen: true
  android_gravity: center
  ios: false
```

But when I ran create splash and build for android, everything was not as expected

![Screen Shot 2021-02-09 at 17 01 35](https://user-images.githubusercontent.com/43400653/107347543-832b0380-6af8-11eb-8719-4308071e141f.png)

The image not full screen, I tried to "fill_vertical" "fill_horizontal" but this image not to scale and be stretched

What's expected:

![Screen Shot 2021-02-09 at 17 04 13](https://user-images.githubusercontent.com/43400653/107347871-de5cf600-6af8-11eb-88aa-d438d8f0543e.png)

**Comment by jonbhanson** [comment] 2021-02-09 12:32
What you are describing is the expected behavior of Android [Center Gravity](https://developer.android.com/reference/android/view/Gravity#CENTER): _"Place the object in the center of its container in both the vertical and horizontal axis, not changing its size."_. Unfortunately I am not aware of a bitmap gravity setting that will scale an image to cover the screen while keeping the aspect ratio.

**Comment by vukhacbiet** [comment] 2021-02-09 14:03
> What you are describing is the expected behavior of Android [Center Gravity](https://developer.android.com/reference/android/view/Gravity#CENTER): _"Place the object in the center of its container in both the vertical and horizontal axis, not changing its size."_. Unfortunately I am not aware of a bitmap gravity setting that will scale an image to cover the screen while keeping the aspect ratio.

Yes, You're right, but I hope "fill_vertical" will made image fill screen by the height, but it is not working as expected, The width is shrinking a bit althougth the height is correct.
![148355171_2887440064825638_4114840630446972351_n](https://user-images.githubusercontent.com/43400653/107374469-3526f780-6b1a-11eb-8054-d17c51d490e0.jpg)

**Comment by BringTheChill** [comment] 2021-02-11 17:29
what about just add fill in launch_background.xml like this?
`<?xml version="1.0" encoding="utf-8"?>

<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@color/splash_color"/>
    <item>
        <bitmap android:gravity="fill" android:src="@drawable/splash"/>
    </item>
</layer-list>
`

**Comment by jonbhanson** [comment] 2021-02-11 18:14
Android's `fill` gravity will stretch to fill the screen, so the aspect ratio will be wrong on some devices.

**Comment by jonbhanson** [comment] 2021-02-19 14:19
@vukhacbiet one solution could be to keep your character the same size, but add more background around the edges.  Then use center gravity.  Size the image to be the same size, but then the edges of the image will go beyond the edges of the screen.  You will have the right aspect ratio, and the image will go to the edge of the screen.  So, for example, if your original image was within the red rectangle, add more background outside the red rectangle:
 
![white-picket-fence14](https://user-images.githubusercontent.com/32202698/108515543-303d1300-7293-11eb-86c8-1004b805ec99.jpg)

**Comment by jonbhanson** [comment] 2021-02-22 15:54
Since this seems to be a shortcoming in Android and which cannot be solved by this plugin, I will close this ticket.  Please feel free to reopen if you need anything further.

**Closed by jonbhanson** 2021-02-22 15:54 UTC
Labels: help wanted

**Comment by phankietit** [comment] 2022-03-03 08:20
Same issue :(

**Comment by BangJihoon** [comment] 2023-01-29 10:54
me neither

**Comment by balu3679** [comment] 2023-01-31 11:16
Same issue :(

**Comment by Fidetro** [comment] 2023-09-03 06:24
same issues,there's no way to fix this?
