### ISSUE TITLE
Question: Is it possible to have progress indicator when displaying splash screen?

### ISSUE THREAD

**Issue by wwyung** [jonbhanson/flutter_native_splash#662] opened 2024-02-14 06:08 UTC
Hi, I am using flutter_native_splash in my app, and I would like to either have a cycling dots, or some other form that indicating progress when splash screen is showing during app startup time. Does this capability exists already today? If so, can someone show me how to do that? Thanks!

**Comment by jonbhanson** [comment] 2024-02-18 15:49
This capability does not exist today.  Closing as it is a duplicate of #619, or #245 (animated loading).

**Closed by jonbhanson** 2024-02-18 15:49 UTC
