### ISSUE TITLE
[BUG] My background has disappeared

### ISSUE THREAD

**Issue by EArminjon** [jonbhanson/flutter_native_splash#130] opened 2021-02-09 18:01 UTC
**Describe the bug**
The background change during second phase of splash screen as you can see on the linked video.
It should be white.

**To Reproduce**
I Didn't know why, on one of my apps it works well... Can't see difference even with same image.

```
flutter_native_splash:
  image: assets/images/icon.png
  color: "FFFFFF"
```

**Screenshots**

**Device (please complete the following information):**
 - MI 9T MIUI 12 Android 10

**Flutter doctor**
```
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [version 10.0.19042.789], locale fr-FR)
    • Flutter version 1.22.6 at C:\Users\engue\Documents\Softwares\flutter
    • Framework revision 9b2d32b605 (3 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Users\engue\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\engue\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Mi 9T (mobile) • c8d2a7bf • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

https://user-images.githubusercontent.com/37028599/107406757-1409db00-6b09-11eb-99f2-c6a8ddbe5b31.mp4

**Comment by jonbhanson** [comment] 2021-02-10 19:32
@EArminjon do you have a second splash page that displays in Flutter while your apps resources load?

**Comment by EArminjon** [comment] 2021-02-11 08:17
@jonbhanson no, I've 5 apps, some do heavy tasks during splash screen. This one do nothing and got this bug :/

**Comment by EArminjon** [comment] 2021-02-11 13:50
In addition, it work well on simulator or on a Huawei with android 7.

**Comment by jonbhanson** [comment] 2021-02-11 14:29
@EArminjon in iOS, there is a problem that happens when the splash screen is changed, which has an effect similar to what you are seeing.  [Stackoverflow thread](https://stackoverflow.com/questions/33002829/ios-keeping-old-launch-screen-and-app-icon-after-update).  I know you are running android, but I think in this case it may be worth it to try the solution anyway:
Uninstall the app, shut down the device, boot up and reinstall.

**Comment by EArminjon** [comment] 2021-02-11 14:35
@jonbhanson I test your solution (uninstall...) same issue. I got the app from the playstore and issue always here.

**Comment by jonbhanson** [comment] 2021-02-11 14:45
I tried running the app and it works ok on my device.  So far the problem only has been found on one device?

**Comment by EArminjon** [comment] 2021-02-11 14:47
@jonbhanson Hum, I can't test on more devices. I need to find some testers.

**Comment by jonbhanson** [comment] 2021-02-18 14:25
@EArminjon since this problem seems to be device specific and we cannot reproduce, I am going to close this ticket.  Please feel free to reopen if you determine steps to reproduce. 👍🏻

**Closed by jonbhanson** 2021-02-18 14:25 UTC
