### ISSUE TITLE
[Question] Using same icon for light and dark mode results in icon darker for dark mode.

### ISSUE THREAD

**Issue by TaylorHo** [jonbhanson/flutter_native_splash#446] opened 2022-11-03 14:42 UTC
Hi,

I'm using the same icon for light mode and dark mode.

When the mobile device is in **light mode**, tha splash screen is with **radiant colors**.
When the mobile device is in **dark mode**, the splash screen is **a lot darker than the light one**.

Why, if it's the same icon and background color?

Should I specify a configuration for dark and light modes, even if the splash screen will be the same?

**Comment by jonbhanson** [comment] 2022-11-03 14:44
Please include 1. your config 2. screen captures of the splash in light and dark modes and 3. your source images.

**Comment by TaylorHo** [comment] 2022-11-04 12:27
Hello, of course. Here:

### 1. Configuration
```
flutter_native_splash:
  color: "#6558f5"
  image: assets/icon/icon-foreground.png
  web: false
```

### 2. Screen Captures
<i>The darker one was taken with the device in Dark Mode</i>
<div style="display: flex; align-items: center; justify-content: center;  flex-direction: row;">
<img src="https://user-images.githubusercontent.com/47436525/199969833-78ab0168-8da9-4fb4-bd6b-87f5bccec1c0.jpg" width="260">
<img src="https://user-images.githubusercontent.com/47436525/199969838-de568712-967d-4b26-b0a1-b52464c47586.jpg" width="260">
</div>


### 3. Source files
_Icon placed at `assets/icon/icon-foreground.png`_
![icon-foreground](https://user-images.githubusercontent.com/47436525/199970098-78a16e92-e916-4fb3-8ae3-678e0436671f.png)

**Comment by jonbhanson** [comment] 2022-11-06 14:10
This package is not able to do what you are seeing.  You have only supplied one color and one image, so those are all this package has to work work with.  It doesn't do anything like modifying the color or image tint.  I think your phone must be applying a filter to the colors to produce this effect.

**Comment by TaylorHo** [comment] 2022-11-10 18:04
Yes, even using a specific color for dark mode (which is the same background and image color as light mode), the device is applying this "dark" overlay. This could be an OS issue (since I am using Xiaomi MIUI OS).

Do you know of a workaround to change this behavior?

**Comment by jonbhanson** [comment] 2022-11-13 14:12
Sorry, I haven't used the Xiaomi MIUI OS.  I will close this ticket since the problem isn't related to this package.

**Closed by jonbhanson** 2022-11-13 14:12 UTC

**Comment by hasanm08** [comment] 2024-04-13 08:39
did you try this?
https://stackoverflow.com/questions/69812590/android-12-splash-screen-icon-not-displaying/69826671#69826671
I tried but had some issues with adding ```androidx.core:core-splashscreen``` in gradle
please notify me on any update
