### ISSUE TITLE
Why different on darkmode?

### ISSUE THREAD

**Issue by And96** [jonbhanson/flutter_native_splash#586] opened 2023-08-26 16:41 UTC
When android dark mode is enabled the splash screen is much darker then when dark mode is off

How to disable this behavior?

**Comment by And96** [comment] 2023-08-26 16:42
Default 

![Screenshot_2023-08-26-18-40-37-472_com.and96.aggregator_news.jpg](https://github.com/jonbhanson/flutter_native_splash/assets/42185838/7ad33b45-10c0-4c14-8c00-a7515eaa1f30)

**Comment by And96** [comment] 2023-08-26 16:42
When dark mode is enabled from system notification toggle

![Screenshot_2023-08-26-18-40-27-365_com.and96.aggregator_news.jpg](https://github.com/jonbhanson/flutter_native_splash/assets/42185838/7a1521f7-f28a-4536-9249-4c8aab4e5b40)

**Comment by And96** [comment] 2023-08-26 16:44
I am using an Android device
Xiaomi with MIUI 14

**Comment by jonbhanson** [comment] 2023-08-27 14:30
This is how MIUI renders apps in dark mode.  Duplicate of #446.

**Comment by And96** [comment] 2023-08-28 19:54
Yes. But... If I check others apps.
Splash screen is not darker with dark mode

E.g: play store, strava, Instagram, gmail, telegram, firefox...

Noone has dark layer above.

**Comment by jonbhanson** [comment] 2023-08-30 03:35
I don't have a Xiaomi device, so I am not able to determine a solution.  If you find a solution, I am happy to implement in this package.

**Comment by And96** [comment] 2023-09-04 18:15
For Kotlin/Java developer
There is a line of code to call:
`getDelegate().setLocalNightMode(AppCompatDelegate.MODE_NIGHT_NO);`
https://stackoverflow.com/a/60564184

IDK how to do this on Flutter/Dart

**Comment by waslost0** [comment] 2023-09-20 08:48
> For Kotlin/Java developer, it is easy to disable darkmode on a single activity.
> 
> There is a line of code to call: `getDelegate().setLocalNightMode(AppCompatDelegate.MODE_NIGHT_NO);`
> 
> https://stackoverflow.com/a/60564184 https://medium.com/androiddevelopers/appcompat-v23-2-daynight-d10f90c83e94
> 
> IDK how to do this on Flutter/Dart

Anyway this isn`t working

**Comment by And96** [comment] 2023-09-20 14:18
> > For Kotlin/Java developer, it is easy to disable darkmode on a single activity.
> > 
> > There is a line of code to call: `getDelegate().setLocalNightMode(AppCompatDelegate.MODE_NIGHT_NO);`
> > 
> > https://stackoverflow.com/a/60564184 https://medium.com/androiddevelopers/appcompat-v23-2-daynight-d10f90c83e94
> > 
> > IDK how to do this on Flutter/Dart
> 
> Anyway this isn`t working

Apps like Gmail, Telegram, Play Store, Instagram, and many others are ok.

Others like, Amazon or other web apps, or flutter ones have this grey filter.

I cannot find a solution actually.

**Comment by jonbhanson** [comment] 2023-10-15 15:08
Since this problem is from the Xiaomi MIUI OS and I am not aware of any way to avoid it, I will close this ticket since the problem isn't related to this package.

**Closed by jonbhanson** 2023-10-15 15:08 UTC
