### ISSUE TITLE
How do you center the image?

### ISSUE THREAD

**Issue by mark8044** [jonbhanson/flutter_native_splash#260] opened 2022-01-05 21:12 UTC
First thanks so much for this project!!

Ive got my BG color and icon working, but Im totally confused how to center the icon, its always showing up at the bottom center

My file as it stands:
```
  branding_mode: center
  android_gravity: center
  ios_content_mode: center
```

And it just refuses to budge from the bottom center.  I know this is probably a really stupid thing I'm missing here...

**Comment by jonbhanson** [comment] 2022-01-05 21:14
Can you include your whole `flutter_native_splash`?

**Comment by mark8044** [comment] 2022-01-05 21:21
> Can you include your whole `flutter_native_splash`?

Im a freaking idiot, I placed the image in branding instead of image.

Fixed now-- Thanks for bearing with me

**Comment by jonbhanson** [comment] 2022-01-05 21:23
No worries.  Now go finish building something awesome! 💪 You rock! 🤘🤩

**Comment by khaiql** [comment] 2022-01-08 00:34
I think my config is correct, but the logo is not centered. See the below image is the native splash screen
![Simulator Screen Shot - iPhone 12 mini - 2022-01-08 at 11 31 13 #4](https://user-images.githubusercontent.com/9031129/148623797-faa49cd2-db0a-44b7-953a-00d985ee280a.png)

And this is the secondary splash screen for loading necessary data 
![Simulator Screen Shot - iPhone 12 mini - 2022-01-08 at 11 31 14](https://user-images.githubusercontent.com/9031129/148623816-13ab335c-52ce-4dfc-be21-e2ab9b1926b2.png)
 
Did I miss anything here?

Config

```
flutter_native_splash:

  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove

  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  color: "#754DB7"
  #background_image: "assets/background.png"

  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing
  # the leading # character.

  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file and should be sized for 4x pixel density.
  image: assets/images/logo.png

  # This property allows you to specify an image used as branding in the splash screen. It must be
  # a png file. Currently, it is only supported for Android and iOS.
  # branding: assets/images/logo.png

  # Specify your branding image for dark mode.
  #branding_dark: assets/dart_dark.png

  # To position the branding image at the bottom of the screen you can use bottom, bottomRight,
  # and bottomLeft. The default values is bottom if not specified or specified something else.
  #
  # Make sure this content mode value should not be similar to android_gravity value and ios_content_mode
  # value.
  # branding_mode: bottom

  # The color_dark, background_image_dark, and image_dark are parameters that set the background
  # and image when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above. If the image_dark parameter is specified, color_dark or
  # background_image_dark must be specified.  color_dark and background_image_dark cannot both be
  # set.
  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png

  # The android, ios and web parameters can be used to disable generating a splash screen on a given
  # platform.
  #android: false
  #ios: false
  #web: false

  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  #android_gravity: center
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  #ios_content_mode: center
  #
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center

  # To hide the notification bar, use the fullscreen parameter.  Has no affect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  #fullscreen: true

  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'
```

**Comment by khaiql** [comment] 2022-01-09 06:54
@jonbhanson could you help with this issue or should I create a new one?

**Comment by jonbhanson** [comment] 2022-01-09 17:08
@khaiql what platform is having this trouble?  Is it Android?  Can you send me a stripped-out shell of the program that I can test?  I cannot see anything wrong with your configuration.  It seems that it should be centered.

**Comment by khaiql** [comment] 2022-01-12 03:52
@jonbhanson it was iOS, I couldn't reproduce it anymore though... I guess we can close it again. Sorry for the noise

**Closed** 2022-01-12 15:30 UTC
