### ISSUE TITLE
Android new splash screen deprecation warning

### ISSUE THREAD

**Issue by Macacoazul01** [jonbhanson/flutter_native_splash#199] opened 2021-08-19 15:20 UTC
Since flutter 2.5.0 this new warning appears on the console:
`A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.`

I don't if it's related to the way the package implements the splash screen or not

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 2.5.0-7.0.pre.156, on Microsoft Windows [versÃ£o 10.0.19043.1165], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.2)
[√] VS Code (version 1.59.0)
[√] Connected device (3 available)

• No issues found!

**Comment by jonbhanson** [comment] 2021-08-30 19:58
This message is not related to this package, but is related to a [change](https://flutter.dev/docs/development/ui/advanced/splash-screen#migrating-from-manifest--activity-defined-custom-splash-screens) in how Flutter handles splash screens in Flutter 2.5, as mentioned by @benjaminhorner .  It is caused by having the following code in your `AndroidManifest.xml`, which was included by default in previous versions of Flutter:

```xml
            <!-- Displays an Android View that continues showing the launch screen
                 Drawable until Flutter paints its first frame, then this splash
                 screen fades out. A splash screen is useful to avoid any visual
                 gap between the end of Android's launch screen and the painting of
                 Flutter's first frame. -->
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
```
The solution is to remove the above code.

**Comment by benjaminhorner** [comment] 2021-08-31 10:19
I think this issue can be closed as the solution posted by @jonbhanson solves it. Also, as noted, this is not related to this package.

**Closed** 2021-09-06 14:33 UTC
