### ISSUE TITLE
Remove Splash Screen on WEB

### ISSUE THREAD

**Issue by carpentierchloe** [jonbhanson/flutter_native_splash#570] opened 2023-07-02 09:58 UTC
The splash screen is well working on ANDROID and IOS, but on the WEB the splash screen does not desappear.

How to fix it or do not show the splash screen on Web ?

I have this config in Yaml.

flutter_native_splash:
  web: false

Thank you very much.

**Comment by jonbhanson** [comment] 2023-08-13 15:38
Do you want to remove the splash screen from your web app altogether, or do you mean you want the splash screen to appear on web and then be removed?

**Comment by jonbhanson** [comment] 2023-08-20 12:55
Duplicate of #536.  Feel free to add any additional information on that ticket.

**Closed by jonbhanson** 2023-08-20 12:55 UTC
