### ISSUE TITLE
removeAfter with Provider initialization

### ISSUE THREAD

**Issue by galvanu** [jonbhanson/flutter_native_splash#288] opened 2022-02-10 11:40 UTC
In my flutter I'm using Provider package for dependency injection.
I want to use the removeAfter feature but the problem I'm facing is that I can't access the injected services before I initialize the app and return MultiProvider widget.
As a result trying to access the services inside the main function throws an error that the service hasn't injected yet.
There is any solution for this scenario?

**Comment by BramDriesen** [comment] 2022-02-13 19:35
Duplicate of https://github.com/flutter/flutter/issues/98241 I think.

**Comment by galvanu** [comment] 2022-02-14 11:43
@BramDriesen can you please explain how its related?

**Comment by BramDriesen** [comment] 2022-02-14 12:20
Because you need packages that can only be accessed from within the RunApp (same as the Amplify API in my example). Meaning you can't show/hide the splash screen with the removeAfter because it's limited to the `main` function which has no access to those packages yet or can not check the `initState`.

**Comment by jonbhanson** [comment] 2022-02-14 13:55
I have released an update that gives more flexibility to make a call to remove the splash screen.  Check out the [readme](https://pub.dev/packages/flutter_native_splash#3-set-up-app-initialization-optional) for an example of how to use.

**Closed** 2022-02-15 12:23 UTC
