### ISSUE TITLE
Splash screen not displaying as full screen image

### ISSUE THREAD

**Issue by vikayo-fincode** [jonbhanson/flutter_native_splash#326] opened 2022-04-01 09:41 UTC
**Describe the bug**
My splash screen is not displaying in Fullscreen mode on my Android device

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

**Flutter doctor**
Please paste the results of the `flutter doctor -v` here

**Additional context**

**Comment by jonbhanson** [comment] 2022-04-01 11:13
The full screen works in the package's example app, so if you don't give any specifics about your device or how to reproduce, I cannot help.

**Comment by jonbhanson** [comment] 2022-04-07 12:11
Closing this ticket due to lack of information.  Feel free to reopen with more details if you still have trouble.

**Closed by jonbhanson** 2022-04-07 12:11 UTC
